export enum SRTErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  STATION_NOT_FOUND = 'STATION_NOT_FOUND',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
  ONLY_SRT_TRAIN = 'ONLY_SRT_TRAIN',
  FAIL_TO_RESERVE = 'FAIL_TO_RESERVE',
  ALREADY_CANCELLED = 'ALREADY_CANCELLED',
  UNKNOWN = 'UNKNOWN',
}
